name: rec_to_binaries
channels:
- conda-forge
dependencies:
- jupyter
- jupyterlab
- matplotlib
- pandas
- numpy
- scipy
- "python >= 3.6"
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- Faker
- pip
- pip:
  - mountainlab-pytools
