name: rec_to_binaries
channels:
- conda-forge
- franklab
dependencies:
- jupyter
- jupyterlab
- matplotlib
- "pandas = 0.24.0"
- numpy
- scipy
- "python >= 3.6"
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- rec_to_binaries
- pip
- pip:
  - mountainlab-pytools
